name: Set env variable

on:
  workflow_dispatch

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Build
        env:
          VITE_REACT_APP_SERVER_URL: https://mern-tasks-app-api.onrender.com
